import type { Payment } from "./types";

export const SAMPLE_PAYMENT: Payment[] = [
  {
    id: "728ed52f",
    amount: 100,
    status: "pending",
    email: "john@example.com",
    createdAt: new Date(2025, 1, 15),
  },
  {
    id: "489e1d42",
    amount: 125,
    status: "processing",
    email: "jane@example.com",
    createdAt: new Date(2025, 2, 20),
  },
  {
    id: "6a37dd12",
    amount: 200,
    status: "success",
    email: "bob@example.com",
    createdAt: new Date(2025, 3, 10),
  },
  {
    id: "f5a21c5e",
    amount: 175,
    status: "failed",
    email: "alice@example.com",
    createdAt: new Date(2025, 3, 25),
  },
  {
    id: "9b5c1b2a",
    amount: 300,
    status: "success",
    email: "charlie@example.com",
    createdAt: new Date(2025, 4, 5),
  },
  {
    id: "3d8f7a2e",
    amount: 450,
    status: "processing",
    email: "dave@example.com",
    createdAt: new Date(2025, 4, 15),
  },
  {
    id: "c6e2d8f1",
    amount: 275,
    status: "pending",
    email: "eve@example.com",
    createdAt: new Date(2025, 5, 1),
  },
  {
    id: "4a9c3b5d",
    amount: 180,
    status: "success",
    email: "frank@example.com",
    createdAt: new Date(2025, 5, 10),
  },
  {
    id: "8e7d6c5b",
    amount: 220,
    status: "failed",
    email: "grace@example.com",
    createdAt: new Date(2025, 6, 1),
  },
  {
    id: "2b1a9c8d",
    amount: 375,
    status: "success",
    email: "henry@example.com",
    createdAt: new Date(2025, 6, 15),
  },
  {
    id: "5f4e3d2c",
    amount: 150,
    status: "pending",
    email: "saddasdasdas@gmail.com",
    createdAt: new Date(2025, 7, 1),
  },
];
