/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TanstackTableQueryImport } from './routes/tanstack-table-query'
import { Route as TanstackRoutingImport } from './routes/tanstack-routing'
import { Route as RechartsImport } from './routes/recharts'
import { Route as FramerMotionImport } from './routes/framer-motion'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TanstackTableQueryRoute = TanstackTableQueryImport.update({
  id: '/tanstack-table-query',
  path: '/tanstack-table-query',
  getParentRoute: () => rootRoute,
} as any)

const TanstackRoutingRoute = TanstackRoutingImport.update({
  id: '/tanstack-routing',
  path: '/tanstack-routing',
  getParentRoute: () => rootRoute,
} as any)

const RechartsRoute = RechartsImport.update({
  id: '/recharts',
  path: '/recharts',
  getParentRoute: () => rootRoute,
} as any)

const FramerMotionRoute = FramerMotionImport.update({
  id: '/framer-motion',
  path: '/framer-motion',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/framer-motion': {
      id: '/framer-motion'
      path: '/framer-motion'
      fullPath: '/framer-motion'
      preLoaderRoute: typeof FramerMotionImport
      parentRoute: typeof rootRoute
    }
    '/recharts': {
      id: '/recharts'
      path: '/recharts'
      fullPath: '/recharts'
      preLoaderRoute: typeof RechartsImport
      parentRoute: typeof rootRoute
    }
    '/tanstack-routing': {
      id: '/tanstack-routing'
      path: '/tanstack-routing'
      fullPath: '/tanstack-routing'
      preLoaderRoute: typeof TanstackRoutingImport
      parentRoute: typeof rootRoute
    }
    '/tanstack-table-query': {
      id: '/tanstack-table-query'
      path: '/tanstack-table-query'
      fullPath: '/tanstack-table-query'
      preLoaderRoute: typeof TanstackTableQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/framer-motion': typeof FramerMotionRoute
  '/recharts': typeof RechartsRoute
  '/tanstack-routing': typeof TanstackRoutingRoute
  '/tanstack-table-query': typeof TanstackTableQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/framer-motion': typeof FramerMotionRoute
  '/recharts': typeof RechartsRoute
  '/tanstack-routing': typeof TanstackRoutingRoute
  '/tanstack-table-query': typeof TanstackTableQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/framer-motion': typeof FramerMotionRoute
  '/recharts': typeof RechartsRoute
  '/tanstack-routing': typeof TanstackRoutingRoute
  '/tanstack-table-query': typeof TanstackTableQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/framer-motion'
    | '/recharts'
    | '/tanstack-routing'
    | '/tanstack-table-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/framer-motion'
    | '/recharts'
    | '/tanstack-routing'
    | '/tanstack-table-query'
  id:
    | '__root__'
    | '/'
    | '/framer-motion'
    | '/recharts'
    | '/tanstack-routing'
    | '/tanstack-table-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FramerMotionRoute: typeof FramerMotionRoute
  RechartsRoute: typeof RechartsRoute
  TanstackRoutingRoute: typeof TanstackRoutingRoute
  TanstackTableQueryRoute: typeof TanstackTableQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FramerMotionRoute: FramerMotionRoute,
  RechartsRoute: RechartsRoute,
  TanstackRoutingRoute: TanstackRoutingRoute,
  TanstackTableQueryRoute: TanstackTableQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/framer-motion",
        "/recharts",
        "/tanstack-routing",
        "/tanstack-table-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/framer-motion": {
      "filePath": "framer-motion.tsx"
    },
    "/recharts": {
      "filePath": "recharts.tsx"
    },
    "/tanstack-routing": {
      "filePath": "tanstack-routing.tsx"
    },
    "/tanstack-table-query": {
      "filePath": "tanstack-table-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
