/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TanstackTableQueryImport } from './routes/tanstack-table-query'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TanstackTableQueryRoute = TanstackTableQueryImport.update({
  id: '/tanstack-table-query',
  path: '/tanstack-table-query',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tanstack-table-query': {
      id: '/tanstack-table-query'
      path: '/tanstack-table-query'
      fullPath: '/tanstack-table-query'
      preLoaderRoute: typeof TanstackTableQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tanstack-table-query': typeof TanstackTableQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tanstack-table-query': typeof TanstackTableQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tanstack-table-query': typeof TanstackTableQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tanstack-table-query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tanstack-table-query'
  id: '__root__' | '/' | '/tanstack-table-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TanstackTableQueryRoute: typeof TanstackTableQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TanstackTableQueryRoute: TanstackTableQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tanstack-table-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tanstack-table-query": {
      "filePath": "tanstack-table-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
